### ISSUE TITLE
Discourage use of Option<Error>

### ISSUE THREAD

**Issue by behnam** [rust-lang/api-guidelines#102]
I'm seeing `Option<Error>` function return types, which are actually something very hard to handle using Rust's core/std libs. Basically, there's no one method to do *expect-to-be-None*. 

Also, IIUC, means that `?` cannot be used on it.

And, there's no single method to convert it to `Result<(), Error>` to handle.

So, maybe we can have a guideline for how to use `Option` vs `Result` and discourage use of `Option<Error>` ?

**Comment by BurntSushi** [comment]
`Option<Error>` is useful for describing a state partial failure.

**Comment by behnam** [comment]
I think partial failures need to use a custom type that also set `#[must_use]`, otherwise it depends on documentation just a bit too much.

**Comment by BurntSushi** [comment]
It would be nice to annotate the method itself if that were possible as `#[must_use]`, since I feel like declaring a custom `Option` is also somewhat unfortunate.

**Comment by BurntSushi** [comment]
Unbeknownst to me, there was actually an RFC proposing the addition of `#[must_use]` to functions/methods, and it was [just recently merged](https://github.com/rust-lang/rfcs/pull/1940). So it seems like we could just wait for that to drop and then apply `#[must_use]` to functions that return partial failures.

@behnam What do you think of renaming this issue? I think it's less about "discourage `Option<Error>`" and more about "create guidelines for reporting partial success/failure."

**Comment by behnam** [comment]
Oh, I didn't realize that the function/method must-use has got a new RFC! That's great!

Sure, @BurntSushi!

With this RFC, the focus of this matter shifts towards "remember to must-use if returning any failure status with a type that's not must-use", for me.

I don't have much clue on what a good API for "partial success/failure" would be.

Here's another example that kept me busy today: `std::fs::ReadDir` has an iterator with `type Item = Result<DirEntry>`, meaning that I can map these values, but cannot use `?` inside the map. So, just to walk inside a dir, I **have to** write a for loop if want to handle possible errors, which are not actually generally expected.

**Comment by KodrAus** [comment]
I can't actually think of an example of an API that returns `Option<Error>`, and would personally be surprised to see it in an API as opposed to `Result<(), Error>`. The `Option` API already bakes in assumptions that `Some` is a "success" variant and `None` is an "error" variant [with methods like `Option::ok_or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or) and its implementation of `Try` so feel like `Option<Error>` should be discouraged in favour of `Result<(), Error>`.
