### ISSUE TITLE
Render checklist as a checklist

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/api-guidelines#131]
The current rendering of the checklist with `○ [ ]` looks janky.

---

![selection_073](https://user-images.githubusercontent.com/1940490/31868668-a6ded8be-b756-11e7-9d4e-2b9257d2e13c.png)

---

I filed https://github.com/azerupi/mdBook/issues/473 to support checklists better in mdBook.

**Comment by jonas-schievink** [comment]
The issue link is now a 404. The checklist rendering seems to be fixed though.
