### ISSUE TITLE
Don't use unstable syntax without some sort of parsing guard

### ISSUE THREAD

**Issue by leoyvens** [rust-lang/api-guidelines#156]
We had a situation in rust-lang/rust#46480 where we had trouble removing support for an unstable syntax in the parser because a popular crate (crossbeam) used the syntax behind a simple feature gate:
```rust
#[cfg(nightly)]
impl UnstableSyntax for .. {}
```
Because we only process `cfg`s after parsing, the `cfg` doesn't help at all in this case, causing de facto stability of the parser's support for unstable syntax. This situation is likely to repeat itself, we must teach lib authors to only use unstable syntax inside a mod that is `cfg`ed at it's declaration, such as:
```rust
#[cfg(nightly)]
mod contains_unstable_syntax;
```
or behind a macro:
```
#[cfg(nightly)]
macro_rules unstable_syntax! { /* expand to unstable syntax */ }

#[cfg(not(nightly))]
macro_rules unstable_syntax! { /* expand to nothing */ }
```

cc @petrochenkov

**Comment by KodrAus** [comment]
Hmm, this is a tricky and subtle situation. Is there any solution to this on the compiler side rather than in libraries? If not, maybe we can frame this as a more general guideline for structuring your library that supports both `stable` and optional `nightly` features?
