### ISSUE TITLE
Crates which re-export types from other crates should also re-export the entire crate

### ISSUE THREAD

**Issue by jsgf** [rust-lang/api-guidelines#170]
For example, `quickcheck` has:
```
extern crate rand;

pub use rand::Rng;
```
This has the problem that all users of `quickcheck` need to depend on the same version of `rand` as `quickcheck` if they want to use the rest of `rand`'s API. If `quickcheck` had:
```
pub extern crate rand;

pub use rand::Rng;
```
then users can use `quickcheck::rand` to get access to the full rand API to interact with `quickcheck`, while not being constrained about what version of rand they want for their own purposes.

**Comment by jsgf** [comment]
https://users.rust-lang.org/t/rfc-api-guideline-re-export-a-whole-crate-if-exporting-any/17820

**Comment by WiSaGaN** [comment]
[This issue](https://github.com/rust-lang-nursery/api-guidelines/issues/176) has more discussion going on currently.

**Comment by KodrAus** [comment]
I'll close this one in favour of #176 to try keep discussion focused.
