### ISSUE TITLE
Broken link to the Rust FAQ

### ISSUE THREAD

**Issue by mattheww** [rust-lang/api-guidelines#191]
`necessities.md` contains the following link, which is now broken:
https://www.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license

As far as I can tell the entire FAQ has been removed without replacement.

**Comment by dtolnay** [comment]
Thanks! I would accept a PR to include whatever useful information used to be in the FAQ into this guideline, or revise this guideline to remove the link.

**Comment by pzmarzly** [comment]
Relevant: https://github.com/rust-lang/www.rust-lang.org/issues/291

The content can be retrieved [on Wayback Machine](http://web.archive.org/web/20180917000516/https://www.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license) or [on prev.rust-lang.org](https://prev.rust-lang.org/en-US/faq.html#why-a-dual-mit-asl2-license) so maybe linking to it would be enough for now. I'd go for Wayback Machine, Rust website broke links once, it may happen again ([link rot](https://en.wikipedia.org/wiki/Link_rot)).

**Comment by dtolnay** [comment]
Fixed in #216.
