### ISSUE TITLE
Document recommendation about Arc::clone(&ref) syntax.

### ISSUE THREAD

**Issue by nical** [rust-lang/api-guidelines#200]
See https://github.com/rust-lang/rust/pull/63252 and https://github.com/rust-lang/rfcs/pull/1954.

**Comment by dtolnay** [comment]
This is a useful recommendation but I don't think it is a great fit for the API guidelines. I would prefer to keep this project focused on public API design, and leave implementation-level tips for a different document. That way we keep the list of guidelines short enough that it's reasonable to run through the whole thing when polishing a crate.
