### ISSUE TITLE
Possible contradiction between the different conversion naming guidelines?

### ISSUE THREAD

**Issue by arnauorriols** [rust-lang/api-guidelines#219]
First of all, apologies in advanced, as there's a good chance the issue is mine, as my journey with Rust is just some weeks old. 

As I see it, there are at least 3 different criteria when naming conversions:
- **cost** ([C-CONV]): name the conversion methods according to the cost of the transformation and whether they take ownership or not
- **abstraction** ([C-CONV]): An addendum to C-CONV states that `as_` and `into_` generally reduce abstraction, while `to_` stays at the same level of abstraction (however, there's no mention of those conversions that increase abstraction?)
- **interoperability** ([C-CONV-TRAITS]): Implementing `From` (which provides an `into_` conversion method) and `AsRef` (which provides an `as_` conversion method) to articulate conversions between types helps the ergonomics of your API (it's one of the main method overloading patterns in Rust?)

These criteria are orthogonal, thus they might get in contradiction, specially in the case of `into_`:
- I want to "deconstruct data into its underlying representation" (`into_`) without taking ownership (`to_`)
- I want to ease the ergonomics of my newtypes implementing `From` (`into_`), but a new type usually implies increasing abstraction (not clear what conversion naming is recommended regarding increase of abstraction). Maybe this is more debatable, but I might want to allow conversions without forcing to take ownership, so that means implementing `From` for "borrowed -> owned (non-Copy types)" (`to_`)
- Examples in [C-CONV-TRAITS] are examples of "owned -> owned (Copy types)" (`to_`), and examples that "stay at the same level of abstraction" (`to_`)
- See more examples in a [discord discussion]

I think these contradictions are the consequences of an oversimplification. What are your thoughts on this? In case I might not be wrong, I would suggest a disclaimer explaining these contradictions, and a clarification that one should chose which criteria to follow based on the priorities of the code being implemented, and that it should not be expected to follow all 3 criteria at once. 

Thank you for your time!

[C-CONV]: https://rust-lang.github.io/api-guidelines/naming.html#c-conv
[C-CONV-TRAITS]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-conv-traits
[discord discussion]: https://discordapp.com/channels/442252698964721669/443150878111694848/701212704236503111

**Comment by dtolnay** [comment]
The criteria aren't orthogonal because anything that violates one of them shouldn't be treated as a conversion. The guideline tries to characterize the cases that should be a conversion.

> - I want to "deconstruct data into its underlying representation" (`into_`) without taking ownership (`to_`)

This would be an accessor. Examples:

- https://doc.rust-lang.org/std/io/struct.BufReader.html#method.get_ref
- https://doc.rust-lang.org/std/thread/struct.Thread.html#method.id

> - I want to ease the ergonomics of my newtypes implementing `From` (`into_`), but a new type usually implies increasing abstraction (not clear what conversion naming is recommended regarding increase of abstraction).

Increasing abstraction should be a constructor on the more specific type. Examples:

- https://doc.rust-lang.org/std/path/struct.Path.html#method.new
- https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8

> - Maybe this is more debatable, but I might want to allow conversions without forcing to take ownership, so that means implementing `From` for "borrowed -> owned (non-Copy types)" (`to_`)

This is not recommended.

> - Examples in C-CONV-TRAITS are examples of "owned -> owned (Copy types)" (`to_`), and examples that "stay at the same level of abstraction" (`to_`)

It's fine for a `From` impl to have those behaviors. The conversion naming guideline applies to associated methods with the name <code>into_<i>something</i>()</code>, not the `From`/`Into` impls.

**Comment by arnauorriols** [comment]
Thanks, that's much clear then.

Am I right then in understanding that other resources like [convenient and idiomatic conversions in Rust] contradict these guidelines? (in this article, particularly in the `SortedVec` example, it proposes to implement `From<&T> for Y` and uses `From` to increase abstraction, where a constructor approach should be used instead).

[convenient and idiomatic conversions in Rust]:  https://ricardomartins.cc/2016/08/03/convenient_and_idiomatic_conversions_in_rust

**Comment by arnauorriols** [comment]
What about a conversion that takes ownership of a non-copy type but transforms data at the same level of abstraction? `into_` or `to_`?
