### ISSUE TITLE
Test for Send/Sync/other traits with where Self: Send + Sync + ...

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/api-guidelines#223]
I think it is better to add a where clause to the struct/enum/union definition which is required to be `Send/Sync/any other trait`.
First, of all, it becomes part of the item declaration and second, it doesn't require compiling the crate with `cfg(test)` for verifying the implementation of the auto traits.

Compare this (taken from [this paragraph](https://rust-lang.github.io/api-guidelines/interoperability.html#types-are-send-and-sync-where-possible-c-send-sync)):

```rust
#[test]
fn test_send() {
    fn assert_send<T: Send>() {}
    assert_send::<MyStrangeType>();
}

#[test]
fn test_sync() {
    fn assert_sync<T: Sync>() {}
    assert_sync::<MyStrangeType>();
}
```

To this:

```rust
struct MyStrangeType
where
    Self: Send + Sync
{
    // ...
}
```

This style doesn't conflict with `clippy` and `rustc` lints.
So how about amending that paragraph with the new guideline?

**Comment by dtolnay** [comment]
This suggestion conflicts badly with trivial_bounds. The following compiles even though the type is neither Send nor Sync.

```rust
#![feature(trivial_bounds)]

struct MyStrangeType
where
    Self: Send + Sync,
{
    ptr: *const u8,
}
```

**Comment by Veetaha** [comment]
I think that this particular case should be added to the **Drawbacks** section of the rfc at least. This is indeed unfortunate, with my proposal the issue would be detected only upon the first type usage...

**Comment by dtolnay** [comment]
> it doesn't require compiling the crate with `cfg(test)` for verifying the implementation of the auto traits.

A better solution for this would be:

```rust
const _: () = {
    fn assert_send<T: Send>() {}
    let _ = assert_send::<MyType>;
};
```

**Comment by Veetaha** [comment]
>A better solution for this would be:

Well, nope, even this should be enough:
```
const _: () = drop::<MyStrangeType>;
```

**Comment by dtolnay** [comment]
I think the current guideline is the approach I prefer most, so I'll go ahead and close this issue.
