### ISSUE TITLE
Justification of html_root_url is missing nuance

### ISSUE THREAD

**Issue by jyn514** [rust-lang/api-guidelines#229]
cc https://github.com/rust-lang/api-guidelines/issues/75, @dtolnay 

From https://github.com/env-logger-rs/env_logger/issues/185:

The scenario where this goes wrong (assuming you're the author of `env_logger` and not using `html_root_url`) is:

1. Another `downstream` crate uses `env_logger` as a dependency
2. `downstream` re-exports or in some other way links to `env_logger`
3. A user or developer of `downstream` builds documentation locally with `cargo doc --no-deps` (without `--extern-html-root-url`, because in practice no one but docs.rs does that).

Then the links to `env_logger` will be broken. But there's a simple fix and the fix is to remove `--no-deps`. Is this really so common that it's worth recommending that library authors use `html_root_url`?

Note that I'm hoping to fix this properly in cargo instead: https://github.com/rust-lang/cargo/issues/8296

**Comment by jyn514** [comment]
Note that this has nothing to do with docs.rs, docs.rs passes `--extern-html-root-url` which always overrides any `html_root_url` you declare yourself.

**Comment by BurntSushi** [comment]
I'm pretty sure this guideline was created in a time where not specifying `html_root_url` was more problematic than it is today. But I can't remember the details to be honest. I don't think I use it in any of my crates and I've never heard any complaints.

**Comment by jyn514** [comment]
Oh hmm - I think when it was originally written rustdoc didn't support `--extern-html-root-url`, so docs.rs did need it. But that's not the case any more.

Should I make a PR removing the recommendation?

**Comment by jyn514** [comment]
Oh heh - it has a comment pointing to https://github.com/rust-lang/rust/issues/42301, which I closed as wontfix a few days ago.

**Comment by BurntSushi** [comment]
> Oh hmm - I think when it was originally written rustdoc didn't support `--extern-html-root-url`, so docs.rs did need it. But that's not the case any more.
> 
> Should I make a PR removing the recommendation?

I'm not even sure docs.rs was even around back then. But I can't remember. :)

**Comment by jhpratt** [comment]
For what it's worth I'm fairly certain most crates (including all of mine) don't use this attribute, and I have _never_ had an issue with links not working exactly as expected.

**Comment by KodrAus** [comment]
Sounds like we should remove the recommendation then! It's a bit of a footgun that we don't need anymore.

**Comment by KodrAus** [comment]
Actually, since we have _just_ been talking about the way we make decisions on this repo I should try actually follow what we set out and kick off an FCP!

@rfcbot fcp merge

I propose we remove the guideline recommending `html_root_url` as it's no longer necessary.

**Comment by KodrAus** [comment]
@rfcbot fcp merge

I propose we remove the guideline recommending `html_root_url` as it's no longer necessary.

**Comment by KodrAus** [comment]
Guess I'd better go find out why @rfcbot doesn't want to hang out here

**Comment by jyn514** [comment]
👀 @rfcbot unchecked @BurntSushi 's checkbox

**Comment by BurntSushi** [comment]
Weird. I just checked it again.

**Comment by KodrAus** [comment]
Oh wow... It did work 😮

**Comment by KodrAus** [comment]
Also note there was some lengthy discussion in #230 about this and its implications for non-Cargo build systems.

**Comment by jyn514** [comment]
It unticked @sfackler 's box too! 😕

**Comment by Kage-Yami** [comment]
My apologies of this is not the right place to raise this... admittedly, this is a minor gripe, given it only affects local documentation, but I personally prefer to use `--no-deps` because I don't like the clutter of crates listed on the left-hand side.

I'll agree it makes sense to reduce the effort involved in making a "good" library, but is there some alternative that keeps these links (even to local documentation of dependencies, if need be), without cluttering the left-hand side?

**Comment by sfackler** [comment]
I also frequently build with `--no-deps`, but at the same time tend to forget to update the html_root_url when cutting new releases so I've started removing them.

One option could be for Cargo to start passing `--extern-html-root-url` based off of the crate's configured docs link (or defaulting to docs.rs) since it already has that information. It wouldn't be totally accurate since the docs link may not point to the index of the rustdocs but it'd be better than nothing.

**Comment by jyn514** [comment]
> I'll agree it makes sense to reduce the effort involved in making a "good" library, but is there some alternative that keeps these links (even to local documentation of dependencies, if need be), without cluttering the left-hand side?

Yes, `-Z rustdoc-map`: https://github.com/rust-lang/cargo/issues/8296

**Comment by Kage-Yami** [comment]
> > I'll agree it makes sense to reduce the effort involved in making a "good" library, but is there some alternative that keeps these links (even to local documentation of dependencies, if need be), without cluttering the left-hand side?
> 
> Yes, `-Z rustdoc-map`: [rust-lang/cargo#8296](https://github.com/rust-lang/cargo/issues/8296)

Given I work solely in Stable, effectively no... but I've watched that issue now (I missed the reference in the OP before).

**Comment by mgeisler** [comment]
> I also frequently build with `--no-deps`, but at the same time tend to forget to update the html_root_url when cutting new releases so I've started removing them.

As a side-note: that is why I created the [version-sync crate](https://crates.io/crates/version-sync). It makes it trivial to add an integration test which will fail if you forget to update the `html_root_url` (or any other piece of text which mentions the version number).

**Comment by jplatte** [comment]
#230 was merged, this can be closed.
