### ISSUE TITLE
Discuss naming conventions for traits

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/api-guidelines#28]
Go has one pretty clear convention for interfaces:

> By convention, one-method interfaces are named by the method name plus an -er suffix or similar modification to construct an agent noun: `Reader`, `Writer`, `Formatter`, `CloseNotifier` etc.

In Rust we have some categories:

- **Imperatives** like `io::Write`, `fmt::Debug`, `clone::Clone`
- **Agent nouns** like `iter::Iterator`, `hash::Hasher`
- **Nouns** like `fmt::Binary`, `ops::Fn`
- **Adjectives** like `marker::Sized`, `panic::UnwindSafe`
- **Preposition** like `convert::Into`, `borrow::ToOwned`

Are there any conventions we can distill out of this or is it a free-for-all?

**Comment by alteous** [comment]
Imperatives should be preferred, especially for traits that perform tasks, since they clearly convey the intention. `io::Read`, `clone::Clone`, `serde::Serialize` are completely unambiguous. For marker traits it doesn't really matter.

Having said that it's disappointing that the standard library chose `Iterator` over `Iterate` or otherwise.

**Comment by Centril** [comment]
Personally, I think `Iterator` and adjectives / agent nouns is right because traits describe *classes of types* as well as *constraints* / *properties* on types. Therefore, I think imperatives should not be preferred.

**Comment by stjepang** [comment]
My feeling is that our trait names have nothing to do with imperatives/nouns/adjectives/etc. Instead, trait names adhere to the following rules:

1. If the trait has a single self-explanatory method (or a set of nearly identical methods), name it after the method: `Clone`, `Hash`, `Default`, `Into`, `Write`, `ToOwned`, `AsRef`, `Extend`.

2. If the trait has no methods, name it after what ability (`Send`, `Sync`, `Copy`) or property (`UnwindSafe`) its implementors have.

3. If the trait has a broader set of methods or a single method that is not self-explanatory, the name should describe either what its implementors are (`Iterator`, `Hasher`, `Fn`, `Error`, `Future`, `Termination`) or what ability/property they have (`AsciiExt`, `fmt::Debug`, `fmt::Binary`).

**Comment by brokenthorn** [comment]
Hey @stjepang, your 1 and 2 points are basically the same idea so you could simplify and lump them together ("if the trait exposes mainly one primary method or property/ability, name it like that method or property..."  followed by examples).

Regarding point 3, describing what implementors **are**, pertains to the previous classification of **agent nouns** but you add simple nouns in the mix as well (`AsciiExt`, `fmt::Debug` and so on) which you call describing what **property/ability** an implementor **has**. I guess your point 3 is all about the **nouns**.

In my opinion you've only simplified the classifications a bit but it might detract from meaning which might impede understanding. I do think though that what should come out of this is a more formal explanation of the rules. The rules should be as simple as possible, but not simpler (to quote Einstein, hehe).

**Comment by stjepang** [comment]
It might also be helpful to write down names of existing traits and fictional traits with slightly different names, then try to guess what would an implementor of each of those traits do. Here's a try...

Iteration over lists:

1. `Iterate` - can be iterated over
2. `Iterator` - iterates over something (*)
3. `Iteration` - is a single iteration or the result of one

Process termination:

1. `Terminate` - can be terminated
2. `Terminator` - terminates something
3. `Termination` - is the process of termination or the result of one (*)

Task execution:

1. `Execute` - can be executed
2. `Executor` - executes something (*)
3. `Execution` - is a single execution or the result of one

Writing bytes:

1. `Write` - can be written to (*)
2. `Writer` - can write to something

Value hashing:

1. `Hash` - can be hashed (*)
2. `Hasher` - can hash something (*)

Stack unwinding:

1. `Unwind` - can be unwound
2. `Unwinder` - can unwind something
3. `Unwinding` - the state or process of unwinding
4. `UnwindSafe` - is safe in the context of unwinding (*)

Sending values to other threads:

1. `Send` - can be sent (*)
2. `Sender` - can send something
3. `SendSafe` - is safe to send (same as 1.)

Unpinning values:

1. `Unpin` - can be unpinned (*)
2. `Unpinner` - can unpin something
3. `UnpinSafe` - is safe to unpin (same as 1.)

(*) traits that actually exist

**Comment by brokenthorn** [comment]
Good idea, @stjepang, to gather some examples. That would definitely help.

From looking at the examples, I come to agree with the initial categorisation even more.

All the variants of some trait are either an attribute of the implementor, something it has intrinsically (like `Hash`, even if the hash is calculated at call time, it is an intrinsic internal property of the object), or some thing it can do (like a skill, a job, like a `Hasher`, a `Sender`, etc.).

All other examples feel the same way to me. I think @dtolnay started with a very good classification when he opened this issue. It only needs formalisation. Further examples of (possibly) non-existant traits help complete the formal definition of official naming schemes.

**Comment by mmastrac** [comment]
Is there an established pattern for third-party crates adding extension traits? For example, we're working on modernizing `rust-timers` which currently has a `FutureExt` trait. This obviously conflicts with the futures-rs builtin extension, which means that users who want to get both extension traits have to jump through hoops and rename one of them:

use ...::FutureExt;
use ...::FutureExt as FutureExtFromTimers;

Any thoughts on a naming convention to avoid this conflict? Or alternatively, is it best to just accept the name conflict and punt it to API users?

Here's a pared down example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e95429439d466dff254454f92851f845

**Comment by Nemo157** [comment]
@mmastrac that can be handled via unnamed imports

```rust
use futures::FutureExt as _;
use rust_timers::FutureExt as _;
```

(though that doesn't help with method name conflicts).
